### ISSUE TITLE
Requires revision to launch pipeline

### ISSUE THREAD

**Issue by adamrtalbot** [seqeralabs/action-tower-launch#13]
Currently, a revision is required to launch the pipeline. This does not happen with the CLI.

The difference seems to be when it calls the launch API the CLI uses the named revision (e.g. `master`) while the action uses the Github SHA. Body of POST request from CLI:

```json
{
    "launch": {
        "id": "7dJuaKrRRQTvT2YqLUd05e",
        "computeEnvId": "REDACTED",
        "pipeline": "https://github.com/nextflow-io/hello",
        "workDir": "s3://redacted",
        "revision": "master",
        "userSecrets": [],
        "workspaceSecrets": [],
        "pullLatest": false,
        "stubRun": false
    }
}
```

From action:

```json
{
    "launch": {
        "id": "7dJuaKrRRQTvT2YqLUd05e",
        "computeEnvId": "REDACTED",
        "runName": "run-tower_d61421728f09961c609c48310e7dbde0c3845bff",
        "pipeline": "https://github.com/nextflow-io/hello",
        "workDir": "s3://redacted",
        "revision": "d61421728f09961c609c48310e7dbde0c3845bff",
        "userSecrets": [],
        "workspaceSecrets": [],
        "paramsText": "{}\n",
        "pullLatest": false,
        "stubRun": false
    }
}
```

**Comment by adamrtalbot** [comment]
The "revision" supplied is actually the Github SHA of the current action, so it doesn't work.

**Comment by adamrtalbot** [comment]
Contamination of `revision` variable somewhere:

```
  with:
    pipeline: hello_world
    workspace_id: ***
    access_token: ***
    compute_env: ***
    run_name: run-tower_1ede7e2323831737c908444d61b7a20cf1dae3f8
    workdir: ***/work/1ede7e2323831737c908444d61b7a20cf1dae3f8
    api_endpoint: https://api.tower.nf
    revision: 1ede7e2323831737c908444d61b7a20cf1dae3f8
    parameters: {}
    wait: false
```
